name: th_composer
version: "1.0"
author: derezzedex
about: Program that encodes files or strings to be later used in the TH challenges
args:
    - input:
        short: i
        long: input
        value_name: FILE
        help: Sets the input file to use
        takes_value: true
        conflicts_with:
          - string
    - string:
        short: s
        long: string
        takes_value: true
        value_name: string
        help: Encode the string
        conflicts_with:
          - input
    - output:
        short: o
        long: output
        value_name: DIRECTORY
        help: Sets a custom output directory
        takes_value: true
    - encode:
        short: e
        long: encode
        required_unless_one: [ decode ]
        conflicts_with:
          - decode
    - decode:
        short: d
        long: decode
        required_unless_one: [ encode ]
        conflicts_with:
          - encode
    - technique:
        help: sets the technique to encode/decode
        value_name: technique
        possible_values: [ morse ]
        index: 1
